server:
  port: 9081

spring:
  redis:
    host: 127.0.0.1
    database: 0
    port: 6379
    password:
    jedis:
      pool:
        max-idle: 200
        min-idle: 0
        max-wait: 1ms
    timeout: 1000
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  messages:
    basename: static/i18n/messages
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true #开启驼峰映射
logging:
  file:
    name: ./logs/spring.log
    max-size: 10MB
    max-history: 7
  level:
    root: debug
